name: manyshot-math
channels:
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - arrow-cpp=16.1.0
  - attrs=24.2.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - datasets=2.19.1
  - dill=0.3.8
  - filelock=3.13.1
  - frozenlist=1.5.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - glog=0.5.0
  - huggingface_hub=0.24.6
  - icu=73.1
  - idna=3.7
  - krb5=1.20.1
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.9.1
  - libcxx=14.0.6
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgrpc=1.62.2
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libprotobuf=4.25.3
  - libssh2=1.11.0
  - libthrift=0.15.0
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - multidict=6.1.0
  - multiprocess=0.70.15
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.15
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.2
  - pip=24.2
  - pyarrow=16.1.0
  - pysocks=1.7.1
  - python=3.11.10
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.66.5
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - wheel=0.44.0
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.11.0
  - zlib=1.2.13
  - zstd=1.5.6
